version: '3.9'

services:
  db:
    image: postgres:14.7
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_DATABASE_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE_NAME}
    container_name: papers_and_notes_db
    volumes:
      - ./postgres:/var/lib/postgresql/data